spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    driver-class-url: jdbc:mysql://127.0.0.1:3306/schema_man
    username: root
    password: 123456
    connection-initial-size: 10
    connection-minimum-size: 10
    connection-maximum-size: 50
    connection-maxwait-time: 6000
    connection-maxactive-time: 6000
    connection-minlive-time: 300000
  mybatis:
    typeAliesPackage: org.bin.schema.entity
    mappers-locations: classpath:mapper/*.xml
redis:
  host: localhost
  port: 6379
  auth: 
  pubsub-subject: realtime-pubsub
  pool-minIdle: 1
  pool-maxIdle: 10
  pool-maxActive: 100
  pool-maxWait: 1000
logging:
  config: classpath:logback-schema.xml

  